import mysql.connector
from mysql.connector import Error
from mysql.connector import errorcode

def convertToBinaryData(filename):
    #Convert digital data to binary format
    with open(filename, 'rb') as file:
        binaryData = file.read()
    return binaryData

connection = mysql.connector.connect(host='localhost',
                             database='medicine',
                             user='root',
                             password='root')

def insertBLOB(hop_id,month,type, photo):
    #print("Inserting BLOB into python_employee table")
    cursor = connection.cursor(prepared=True)
    sql_insert_blob_query = """ INSERT INTO `images1`(`hos_id`, `month`, `type`, `photo`) VALUES (%s,%s,%s,%s)"""
    empPicture = convertToBinaryData(photo)   
    # Convert data into tuple format
    insert_blob_tuple = (hop_id,month,type,empPicture)
    result  = cursor.execute(sql_insert_blob_query, insert_blob_tuple)
    connection.commit()
    #print ("Image and file inserted successfully as a BLOB into python_employee table", result)

insertBLOB(101,"JAN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Descriptive\\jan_descriptive.png")
insertBLOB(101,"FEB","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Descriptive\\feb_descriptive.png")
insertBLOB(101,"MAR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Descriptive\\mar_descriptive.png")
insertBLOB(101,"APR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Descriptive\\apr_descriptive.png")
insertBLOB(101,"MAY","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Descriptive\\may_descriptive.png")
insertBLOB(101,"JUN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Descriptive\\jun_descriptive.png")
insertBLOB(101,"JUL","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Descriptive\\jul_descriptive.png")
insertBLOB(101,"AUG","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Descriptive\\aug_descriptive.png")
insertBLOB(101,"SEP","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Descriptive\\sep_descriptive.png")
insertBLOB(101,"OCT","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Descriptive\\oct_descriptive.png")
insertBLOB(101,"NOV","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Descriptive\\nov_descriptive.png")
insertBLOB(101,"DEC","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Descriptive\\dec_descriptive.png")

insertBLOB(102,"JAN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Descriptive\\jan_descriptive.png")
insertBLOB(102,"FEB","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Descriptive\\feb_descriptive.png")
insertBLOB(102,"MAR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Descriptive\\mar_descriptive.png")
insertBLOB(102,"APR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Descriptive\\apr_descriptive.png")
insertBLOB(102,"MAY","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Descriptive\\may_descriptive.png")
insertBLOB(102,"JUN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Descriptive\\jun_descriptive.png")
insertBLOB(102,"JUL","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Descriptive\\jul_descriptive.png")
insertBLOB(102,"AUG","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Descriptive\\aug_descriptive.png")
insertBLOB(102,"SEP","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Descriptive\\sep_descriptive.png")
insertBLOB(102,"OCT","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Descriptive\\oct_descriptive.png")
insertBLOB(102,"NOV","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Descriptive\\nov_descriptive.png")
insertBLOB(102,"DEC","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Descriptive\\dec_descriptive.png")

insertBLOB(103,"JAN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Descriptive\\jan_descriptive.png")
insertBLOB(103,"FEB","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Descriptive\\feb_descriptive.png")
insertBLOB(103,"MAR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Descriptive\\mar_descriptive.png")
insertBLOB(103,"APR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Descriptive\\apr_descriptive.png")
insertBLOB(103,"MAY","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Descriptive\\may_descriptive.png")
insertBLOB(103,"JUN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Descriptive\\jun_descriptive.png")
insertBLOB(103,"JUL","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Descriptive\\jul_descriptive.png")
insertBLOB(103,"AUG","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Descriptive\\aug_descriptive.png")
insertBLOB(103,"SEP","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Descriptive\\sep_descriptive.png")
insertBLOB(103,"OCT","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Descriptive\\oct_descriptive.png")
insertBLOB(103,"NOV","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Descriptive\\nov_descriptive.png")
insertBLOB(103,"DEC","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Descriptive\\dec_descriptive.png")

insertBLOB(104,"JAN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Descriptive\\jan_descriptive.png")
insertBLOB(104,"FEB","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Descriptive\\feb_descriptive.png")
insertBLOB(104,"MAR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Descriptive\\mar_descriptive.png")
insertBLOB(104,"APR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Descriptive\\apr_descriptive.png")
insertBLOB(104,"MAY","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Descriptive\\may_descriptive.png")
insertBLOB(104,"JUN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Descriptive\\jun_descriptive.png")
insertBLOB(104,"JUL","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Descriptive\\jul_descriptive.png")
insertBLOB(104,"AUG","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Descriptive\\aug_descriptive.png")
insertBLOB(104,"SEP","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Descriptive\\sep_descriptive.png")
insertBLOB(104,"OCT","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Descriptive\\oct_descriptive.png")
insertBLOB(104,"NOV","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Descriptive\\nov_descriptive.png")
insertBLOB(104,"DEC","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Descriptive\\dec_descriptive.png")

insertBLOB(105,"JAN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Descriptive\\jan_descriptive.png")
insertBLOB(105,"FEB","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Descriptive\\feb_descriptive.png")
insertBLOB(105,"MAR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Descriptive\\mar_descriptive.png")
insertBLOB(105,"APR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Descriptive\\apr_descriptive.png")
insertBLOB(105,"MAY","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Descriptive\\may_descriptive.png")
insertBLOB(105,"JUN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Descriptive\\jun_descriptive.png")
insertBLOB(105,"JUL","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Descriptive\\jul_descriptive.png")
insertBLOB(105,"AUG","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Descriptive\\aug_descriptive.png")
insertBLOB(105,"SEP","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Descriptive\\sep_descriptive.png")
insertBLOB(105,"OCT","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Descriptive\\oct_descriptive.png")
insertBLOB(105,"NOV","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Descriptive\\nov_descriptive.png")
insertBLOB(105,"DEC","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Descriptive\\dec_descriptive.png")

insertBLOB(106,"JAN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Descriptive\\jan_descriptive.png")
insertBLOB(106,"FEB","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Descriptive\\feb_descriptive.png")
insertBLOB(106,"MAR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Descriptive\\mar_descriptive.png")
insertBLOB(106,"APR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Descriptive\\apr_descriptive.png")
insertBLOB(106,"MAY","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Descriptive\\may_descriptive.png")
insertBLOB(106,"JUN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Descriptive\\jun_descriptive.png")
insertBLOB(106,"JUL","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Descriptive\\jul_descriptive.png")
insertBLOB(106,"AUG","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Descriptive\\aug_descriptive.png")
insertBLOB(106,"SEP","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Descriptive\\sep_descriptive.png")
insertBLOB(106,"OCT","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Descriptive\\oct_descriptive.png")
insertBLOB(106,"NOV","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Descriptive\\nov_descriptive.png")
insertBLOB(106,"DEC","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Descriptive\\dec_descriptive.png")

insertBLOB(107,"JAN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Descriptive\\jan_descriptive.png")
insertBLOB(107,"FEB","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Descriptive\\feb_descriptive.png")
insertBLOB(107,"MAR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Descriptive\\mar_descriptive.png")
insertBLOB(107,"APR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Descriptive\\apr_descriptive.png")
insertBLOB(107,"MAY","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Descriptive\\may_descriptive.png")
insertBLOB(107,"JUN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Descriptive\\jun_descriptive.png")
insertBLOB(107,"JUL","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Descriptive\\jul_descriptive.png")
insertBLOB(107,"AUG","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Descriptive\\aug_descriptive.png")
insertBLOB(107,"SEP","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Descriptive\\sep_descriptive.png")
insertBLOB(107,"OCT","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Descriptive\\oct_descriptive.png")
insertBLOB(107,"NOV","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Descriptive\\nov_descriptive.png")
insertBLOB(107,"DEC","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Descriptive\\dec_descriptive.png")

insertBLOB(108,"JAN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Descriptive\\jan_descriptive.png")
insertBLOB(108,"FEB","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Descriptive\\feb_descriptive.png")
insertBLOB(108,"MAR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Descriptive\\mar_descriptive.png")
insertBLOB(108,"APR","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Descriptive\\apr_descriptive.png")
insertBLOB(108,"MAY","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Descriptive\\may_descriptive.png")
insertBLOB(108,"JUN","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Descriptive\\jun_descriptive.png")
insertBLOB(108,"JUL","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Descriptive\\jul_descriptive.png")
insertBLOB(108,"AUG","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Descriptive\\aug_descriptive.png")
insertBLOB(108,"SEP","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Descriptive\\sep_descriptive.png")
insertBLOB(108,"OCT","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Descriptive\\oct_descriptive.png")
insertBLOB(108,"NOV","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Descriptive\\nov_descriptive.png")
insertBLOB(108,"DEC","Descriptive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Descriptive\\dec_descriptive.png")

################## Predictive#####################################

insertBLOB(101,"JAN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Predictive\\jan_predictive.png")
insertBLOB(101,"FEB","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Predictive\\feb_predictive.png")
insertBLOB(101,"MAR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Predictive\\mar_predictive.png")
insertBLOB(101,"APR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Predictive\\apr_predictive.png")
insertBLOB(101,"MAY","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Predictive\\may_predictive.png")
insertBLOB(101,"JUN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Predictive\\jun_predictive.png")
insertBLOB(101,"JUL","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Predictive\\jul_predictive.png")
insertBLOB(101,"AUG","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Predictive\\aug_predictive.png")
insertBLOB(101,"SEP","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Predictive\\sep_predictive.png")
insertBLOB(101,"OCT","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Predictive\\oct_predictive.png")
insertBLOB(101,"NOV","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Predictive\\nov_predictive.png")
insertBLOB(101,"DEC","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital1\\Medicine\\Predictive\\dec_predictive.png")

insertBLOB(102,"JAN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Predictive\\jan_predictive.png")
insertBLOB(102,"FEB","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Predictive\\feb_predictive.png")
insertBLOB(102,"MAR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Predictive\\mar_predictive.png")
insertBLOB(102,"APR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Predictive\\apr_predictive.png")
insertBLOB(102,"MAY","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Predictive\\may_predictive.png")
insertBLOB(102,"JUN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Predictive\\jun_predictive.png")
insertBLOB(102,"JUL","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Predictive\\jul_predictive.png")
insertBLOB(102,"AUG","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Predictive\\aug_predictive.png")
insertBLOB(102,"SEP","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Predictive\\sep_predictive.png")
insertBLOB(102,"OCT","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Predictive\\oct_predictive.png")
insertBLOB(102,"NOV","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Predictive\\nov_predictive.png")
insertBLOB(102,"DEC","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital2\\Medicine\\Predictive\\dec_predictive.png")

insertBLOB(103,"JAN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Predictive\\jan_predictive.png")
insertBLOB(103,"FEB","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Predictive\\feb_predictive.png")
insertBLOB(103,"MAR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Predictive\\mar_predictive.png")
insertBLOB(103,"APR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Predictive\\apr_predictive.png")
insertBLOB(103,"MAY","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Predictive\\may_predictive.png")
insertBLOB(103,"JUN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Predictive\\jun_predictive.png")
insertBLOB(103,"JUL","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Predictive\\jul_predictive.png")
insertBLOB(103,"AUG","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Predictive\\aug_predictive.png")
insertBLOB(103,"SEP","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Predictive\\sep_predictive.png")
insertBLOB(103,"OCT","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Predictive\\oct_predictive.png")
insertBLOB(103,"NOV","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Predictive\\nov_predictive.png")
insertBLOB(103,"DEC","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital3\\Medicine\\Predictive\\dec_predictive.png")

insertBLOB(104,"JAN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Predictive\\jan_predictive.png")
insertBLOB(104,"FEB","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Predictive\\feb_predictive.png")
insertBLOB(104,"MAR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Predictive\\mar_predictive.png")
insertBLOB(104,"APR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Predictive\\apr_predictive.png")
insertBLOB(104,"MAY","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Predictive\\may_predictive.png")
insertBLOB(104,"JUN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Predictive\\jun_predictive.png")
insertBLOB(104,"JUL","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Predictive\\jul_predictive.png")
insertBLOB(104,"AUG","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Predictive\\aug_predictive.png")
insertBLOB(104,"SEP","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Predictive\\sep_predictive.png")
insertBLOB(104,"OCT","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Predictive\\oct_predictive.png")
insertBLOB(104,"NOV","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Predictive\\nov_predictive.png")
insertBLOB(104,"DEC","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital4\\Medicine\\Predictive\\dec_predictive.png")

insertBLOB(105,"JAN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Predictive\\jan_predictive.png")
insertBLOB(105,"FEB","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Predictive\\feb_predictive.png")
insertBLOB(105,"MAR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Predictive\\mar_predictive.png")
insertBLOB(105,"APR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Predictive\\apr_predictive.png")
insertBLOB(105,"MAY","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Predictive\\may_predictive.png")
insertBLOB(105,"JUN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Predictive\\jun_predictive.png")
insertBLOB(105,"JUL","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Predictive\\jul_predictive.png")
insertBLOB(105,"AUG","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Predictive\\aug_predictive.png")
insertBLOB(105,"SEP","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Predictive\\sep_predictive.png")
insertBLOB(105,"OCT","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Predictive\\oct_predictive.png")
insertBLOB(105,"NOV","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Predictive\\nov_predictive.png")
insertBLOB(105,"DEC","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital5\\Medicine\\Predictive\\dec_predictive.png")

insertBLOB(106,"JAN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Predictive\\jan_predictive.png")
insertBLOB(106,"FEB","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Predictive\\feb_predictive.png")
insertBLOB(106,"MAR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Predictive\\mar_predictive.png")
insertBLOB(106,"APR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Predictive\\apr_predictive.png")
insertBLOB(106,"MAY","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Predictive\\may_predictive.png")
insertBLOB(106,"JUN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Predictive\\jun_predictive.png")
insertBLOB(106,"JUL","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Predictive\\jul_predictive.png")
insertBLOB(106,"AUG","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Predictive\\aug_predictive.png")
insertBLOB(106,"SEP","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Predictive\\sep_predictive.png")
insertBLOB(106,"OCT","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Predictive\\oct_predictive.png")
insertBLOB(106,"NOV","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Predictive\\nov_predictive.png")
insertBLOB(106,"DEC","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital6\\Medicine\\Predictive\\dec_predictive.png")

insertBLOB(107,"JAN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Predictive\\jan_predictive.png")
insertBLOB(107,"FEB","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Predictive\\feb_predictive.png")
insertBLOB(107,"MAR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Predictive\\mar_predictive.png")
insertBLOB(107,"APR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Predictive\\apr_predictive.png")
insertBLOB(107,"MAY","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Predictive\\may_predictive.png")
insertBLOB(107,"JUN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Predictive\\jun_predictive.png")
insertBLOB(107,"JUL","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Predictive\\jul_predictive.png")
insertBLOB(107,"AUG","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Predictive\\aug_predictive.png")
insertBLOB(107,"SEP","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Predictive\\sep_predictive.png")
insertBLOB(107,"OCT","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Predictive\\oct_predictive.png")
insertBLOB(107,"NOV","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Predictive\\nov_predictive.png")
insertBLOB(107,"DEC","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital7\\Medicine\\Predictive\\dec_predictive.png")

insertBLOB(108,"JAN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Predictive\\jan_predictive.png")
insertBLOB(108,"FEB","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Predictive\\feb_predictive.png")
insertBLOB(108,"MAR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Predictive\\mar_predictive.png")
insertBLOB(108,"APR","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Predictive\\apr_predictive.png")
insertBLOB(108,"MAY","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Predictive\\may_predictive.png")
insertBLOB(108,"JUN","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Predictive\\jun_predictive.png")
insertBLOB(108,"JUL","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Predictive\\jul_predictive.png")
insertBLOB(108,"AUG","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Predictive\\aug_predictive.png")
insertBLOB(108,"SEP","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Predictive\\sep_predictive.png")
insertBLOB(108,"OCT","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Predictive\\oct_predictive.png")
insertBLOB(108,"NOV","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Predictive\\nov_predictive.png")
insertBLOB(108,"DEC","Predictive", "C:\\Users\\Mohamed\\Desktop\\Output\\Hospital8\\Medicine\\Predictive\\dec_predictive.png")



connection.close()


